version: "3.8"

services:

  shotener_db:
    image: mysql
    container_name: mysql_shortener
    hostname: mysql_shortener
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes: 
      - ${LOCAL_DB_BACKUP}:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}

  rest_api:
    build: ./shortener-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./shortener-backend:/code
    ports:
      - "8181:8000"
    depends_on:
      - shotener_db

  frontend:
    build: ./shortener-frontend/app
    command: npm run dev
    ports:
      - "3030:3000"
    volumes:
      - ./shortener-frontend/app:/code
    depends_on:
      - rest_api

volumes:
  postgres_database: 
    external: false
