# Generated by Django 4.0.5 on 2022-06-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('url_temporaria', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=32)),
            ],
        ),
    ]
