# Generated by Django 4.0.5 on 2022-06-21 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id_shortener', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('url_temporaria', models.BooleanField(default=False)),
            ],
        ),
    ]
