# Generated by Django 4.0.5 on 2022-06-15 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id_shortener', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=2000)),
                ('url_shortener', models.CharField(max_length=520)),
                ('url_temporaria', models.BooleanField()),
                ('url_clicks', models.IntegerField()),
                ('ip_user', models.CharField(max_length=255)),
            ],
        ),
    ]
