# Generated by Django 4.0.5 on 2022-06-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='url_checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='url_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='url_temporaria',
            field=models.BooleanField(default=False),
        ),
    ]
