# Generated by Django 4.0.5 on 2022-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_remove_shortener_ip_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='url_shortener',
            field=models.URLField(default='http://localhost:8000', max_length=520),
        ),
    ]
