# Generated by Django 4.0.5 on 2022-06-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_rename_views_accesse_shortener_views_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortener',
            old_name='url_temporaria',
            new_name='url_temporary',
        ),
    ]
