# Generated by Django 4.0.5 on 2022-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_alter_shortener_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='url',
            field=models.URLField(),
        ),
    ]
