# Generated by Django 4.0.5 on 2022-06-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_alter_shortener_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='url_shortener',
            field=models.URLField(max_length=520),
        ),
    ]
