# Generated by Django 4.0.5 on 2022-06-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_alter_shortener_url_shortener'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortener',
            old_name='id_shortener',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='shortener',
            name='url_shortener',
        ),
    ]
