# Generated by Django 4.0.5 on 2022-06-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_rename_id_shortener_shortener_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortener',
            old_name='id',
            new_name='id_shortener',
        ),
    ]
